Cleaner Tiles
gavinmccabe/Swift-Classes-Check pull request #11
Opened 2020-11-30 20:48 UTC by Jminding

2020-11-30 20:50 UTC, Jminding commented
![](https://github.trello.services/images/mini-trello-icon.png) [Your Cleaner Tile](https://trello.com/c/jdhv7HlJ/38-your-cleaner-tile)

2020-11-30 22:25 UTC, gavinmccabe requested changes

2020-11-30 22:25 UTC, gavinmccabe commented on Wireframes/Wireframes/CleanerTile.swift
> +                    Text(">")
Use an image here (use `systemName: chevron.forward`)

2020-11-30 22:25 UTC, gavinmccabe commented on Wireframes/Wireframes/CleanerTile.swift
> +}
Consider renaming this file to be a little more useful (since it's not the final tile).  Maybe something like `CleanerTileText.swift` and rename `YourCleanerTile.swift` to `CleanerTile.swift`.  This is because then the final version is given by `CleanerTile()`.  Additionally, when a view is comprised of multiple views like this, combine them in a group (aka a folder) called `CleanerTile`.  This helps keep the project folder nice and tidy when we have hundreds of files like this.

2020-11-30 22:25 UTC, gavinmccabe commented on Wireframes/Wireframes/MapView.swift
> +}
Do not use `MapView()`.  Look at the Trello card, I gave you an image to use as the background.

2020-11-30 22:30 UTC, Jminding commented on Wireframes/Wireframes/MapView.swift
> +}
Ohhh

2020-12-01 00:54 UTC, Jminding commented on Wireframes/Wireframes/CleanerTile.swift
> +}
the WHAT
HUNDREDS OF FILES??? ;-;

2020-12-01 01:20 UTC, gavinmccabe requested changes
I've committed one change to the code you need before you continue working.  Please be sure to pull it before continuing.

2020-12-01 01:20 UTC, gavinmccabe commented on Wireframes/Wireframes/Cleaner Tiles/CleanerTileText.swift
> +}
Put some spacers or padding around the objects so they're not pushed up against the sides like this.  Don't just put padding and spacers all over the place, put them in the places where they make sense, no more, no less.

2020-12-01 01:20 UTC, gavinmccabe commented on Wireframes/Wireframes/Cleaner Tiles/MapView.swift
> +        Image("map_bg")
This file isn't necessary.  If it's just holding something as simple as an image, don't make it a separate file, combine it with one of the others.

2020-12-01 01:20 UTC, gavinmccabe commented on Wireframes/Wireframes/Cleaner Tiles/CleanerTileButton.swift
> +            CleanerTileText(cleanerName: cleanerName, cleanerAddress: cleanerAddress)
I updated this to be `CleanerTileText` rather than `CleanerTile` (since you renamed that file).  Be sure to pull my changes before continuing to work.

2020-12-01 03:45 UTC, Jminding commented
asnaobwoebnawlebwabwaebawebawe

2020-12-01 03:45 UTC, Jminding commented
```swift
//
//  NavBar.swift
//  WireframeNavBar
//
//  Created by Jaymin Ding on 11/30/20.
//

import SwiftUI

struct NavBar: View {
    var body: some View {
        VStack(){
            Spacer()
            ZStack(){
                RoundedRectangle(cornerRadius: 10)
                    .foregroundColor(.white)
                    .frame(width: UIScreen.main.bounds.width, height: 50)
                HStack(){
                    HomeButton()
                    Spacer()
                    OrderButton()
                    Spacer()
                    SettingsButton()
                    Spacer()
                    WalletButton()
                    Spacer()
                    VStack(){
                        
                        PlusButton()
                        Spacer()
                            .frame(height: 10)
                        
                    }
                }
            }
        }
    }
}

struct NavBar_Previews: PreviewProvider {
    static var previews: some View {
        NavBar()
    }
}
```

2020-12-01 03:53 UTC, merged